version: '2'

services:
  # Контейнер с Node.js
  app:
    build:
      context: ./backend
      target: dev
    tty: true
    working_dir: /opt/server
    volumes:
      - ./backend:/opt/server
      - ./static:/opt/static
#    env_file:
#      - .env
    expose:
      - '3000'
    depends_on:
      - mongodb

  # Контейнер с базой данных
  mongodb:
    image: mongo:latest
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: "secret"
#      MONGO_INITDB_ROOT_PASSWORD: "980293098"
    ports:
      - '27017'
    volumes:
      - ./mongo:/data/db


  # Контейнер с nginx
  nginx:
    container_name: proxy_nginx
    depends_on:
      - app
      - mongodb
#      - pgadmin
    image: nginx:latest
    ports:
      - '8081:80'
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./static:/var/www/static
    restart: always

  # Контейнер с pgadmin
#  pgadmin:
#    container_name: pgadmin
#    depends_on:
#      - db
#    image: dpage/pgadmin4
#    environment:
#      PGADMIN_DEFAULT_EMAIL: kirdro@yandex.ru
#      PGADMIN_DEFAULT_PASSWORD: Kirdro989198
#    expose:
#      - '80'
#    restart: always